title: Web Dev Journey
author: Sarah Schilz
email: sarahschilz88@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I am currently learning how to become a front-end web developer and by getting more familiar with Github it will enable me to make projects to show for future employer opportunites.

# social links
instagram_username: schz.dev
github_username:  schz25

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
